<?php


namespace app\admin\controller;


use think\Controller;

class Base extends Controller
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if(!session('?admin.id')){
            return $this->redirect('Index/index');
        }
    }
}
