<?php

namespace app\admin\controller;

use app\common\model\Admin;
use think\App;
use think\Controller;

class Index extends Controller
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if (session('?admin.username')){
            $this->redirect('Home/index');
        }
    }

    // 登录页面
    public function index() {
        return view();
    }

    // 登录操作
    public function dologin(){
        if (request()->isAjax()) {
            $data = [
                'username' => input('username'),
                'password' => input('password')
            ];
            $result = model('Admin')->dologin($data);

            if ($result == 1) {
                 $this->success('登录成功', 'home/index');
            }else {
                 $this->error($result);
            }
        }
    }
}
